[both]
emi = 0.5
tsurf_file = "/home/marekbrodke/OneDrive/Research/sparta/fea/Elmer_Case/surf.temperature"

[sparta]
nevery = 3
groupID = "all"
mixID = "all"
customID = "temperature"

[elmer]
exe = "/home/marekbrodke/Documents/Apps/elmer/install/bin/ElmerSolver"
sif = "/home/marekbrodke/OneDrive/Research/sparta/fea/Elmer_Case/case.sif"
meshDBstem = "/home/marekbrodke/OneDrive/Research/sparta/fea/Elmer_Case/mesh"

[elmer.header]
Mesh_DB = [".", "."]
Include_Path = ""
Results_Directory = ""

[elmer.simulation]
Max_Output_Level = 5
Coordinate_System = "Cartesian"
Coordinate_Mapping = [1, 2, 3]
Simulation_Type = "Transient"
Steady_State_Max_Iterations = 10
Output_Intervals = [100]
Timestep_intervals = [10000]
Timestep_Sizes = [1]
Timestepping_Method = "BDF"
BDF_Order = 2.0
Solver_Input_File = "case.sif"
Output_File = "case.dat"
Post_File = "case.vtu"

[elmer.constants]
Gravity = [0, -1, 0, 9.82]
Stefan_Boltzmann = 5.670374419e-8
Permittivity_of_Vacuum = 8.85418781e-12
Permeability_of_Vacuum = 1.25663706e-6
Boltzmann_Constant = 1.380649e-23
Unit_Charge = 1.6021766e-19

[elmer.solver.1]
Equation = "Heat Equation"
Procedure = ["\"HeatSolve\"", "\"HeatSolver\""]
Variable = "Temperature"
Exec_Solver = "Always"
Stabilize = true
Optimize_Bandwidth = true
Steady_State_Convergence_Tolerance = 1.0e-5
Nonlinear_System_Convergence_Tolerance = 1.0e-7
Nonlinear_System_Max_Iterations = 20
Nonlinear_System_Newton_After_Iterations = 3
Nonlinear_System_Newton_After_Tolerance = 1.0e-3
Nonlinear_System_Relaxation_Factor = 1
Linear_System_Solver = "Iterative"
Linear_System_Iterative_Method = "BiCGStab"
Linear_System_Max_Iterations = 500
Linear_System_Convergence_Tolerance = 1.0e-10
BiCGstabl_polynomial_degree = 2
Linear_System_Preconditioning = "ILU0"
Linear_System_ILUT_Tolerance = 1.0e-3
Linear_System_Abort_Not_Converged = false
Linear_System_Residual_Output = 10

[elmer.equation.1]
Name = "Equation 1"
Active_Solvers = [1]

[elmer.material.1]
Name = "Steel (alloy - generic)"
Poisson_ratio = 0.285
Heat_Capacity = 976.0
Density = 7850.0
Youngs_modulus = 200.0e9
Heat_expansion_Coefficient = 12.0e-6
Sound_speed = 5100.0
Heat_Conductivity = 37.2

[elmer.body.1]
Target_Bodies = [1]
Name = "Body 1"
Equation = 1
Material = 1
Initial_condition = 1


[elmer.initial_condition.1]
Name = "InitialCondition 1"
Temperature = 200

[elmer.boundary_condition.1]
Target_Boundaries = [1, 2]
Name = "BoundaryCondition 1"
Heat_Flux_BC = true
Heat_Flux = 100000
